import { useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

import {
  FaRobot,
  FaBriefcase,
  FaUserGraduate,
  FaMagic,
  FaCheckCircle,
  FaArrowRight,
  FaClipboardList,
  FaClock,
} from "react-icons/fa";

const Interview = () => {
  const [role, setRole] = useState("");
  const [experience, setExperience] = useState("");
  const [loading, setLoading] = useState(false);

  const [questions, setQuestions] = useState([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [completed, setCompleted] = useState(false);

  const generateInterview = async () => {
    if (!role || !experience) {
      return toast.error("Please fill all fields");
    }

    try {
      setLoading(true);

      const token = localStorage.getItem("token");

      const res = await axios.post(
        `${import.meta.env.VITE_API_URL}/interview/generate`,
        {
          role,
          experience,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setQuestions(res.data.questions || []);
      setCurrentQuestion(0);
      setCompleted(false);

      toast.success("Interview Questions Generated");
    } catch (error) {
      console.log(error);

      toast.error(
        error.response?.data?.message ||
          "Failed to generate interview"
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-100">

      <div className="max-w-7xl mx-auto px-6 py-12">

        {/* Hero */}

        <div className="bg-gradient-to-r from-blue-700 via-indigo-700 to-purple-700 rounded-3xl shadow-2xl text-white p-10">

          <div className="flex justify-between items-center flex-wrap gap-6">

            <div>

              <h1 className="text-5xl font-extrabold">
                🎤 AI Mock Interview
              </h1>

              <p className="mt-4 text-blue-100 text-lg">
                Practice interview questions generated by AI based on your target role.
              </p>

            </div>

            <FaRobot className="text-8xl opacity-30 hidden lg:block" />

          </div>

        </div>

        {/* Main Grid */}

        <div className="grid lg:grid-cols-3 gap-8 mt-10">

          {/* Left */}

          <div className="lg:col-span-2 bg-white rounded-3xl shadow-xl p-8">

            <h2 className="text-3xl font-bold mb-8">
              Interview Setup
            </h2>

            <div className="grid md:grid-cols-2 gap-6">

              <div>

                <label className="flex items-center gap-2 font-semibold mb-2">

                  <FaBriefcase className="text-blue-600" />

                  Job Role

                </label>

                <input
                  type="text"
                  placeholder="Example: MERN Stack Developer"
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                  className="w-full border-2 border-gray-200 rounded-xl p-4 focus:border-blue-600 outline-none"
                />

              </div>

              <div>

                <label className="flex items-center gap-2 font-semibold mb-2">

                  <FaUserGraduate className="text-green-600" />

                  Experience

                </label>

                <input
                  type="text"
                  placeholder="Example: Fresher / 2 Years"
                  value={experience}
                  onChange={(e) => setExperience(e.target.value)}
                  className="w-full border-2 border-gray-200 rounded-xl p-4 focus:border-blue-600 outline-none"
                />

              </div>

            </div>

            <button
              onClick={generateInterview}
              disabled={loading}
              className={`w-full mt-8 py-4 rounded-2xl text-xl font-bold text-white flex justify-center items-center gap-3 transition ${
                loading
                  ? "bg-gray-400 cursor-not-allowed"
                  : "bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-700 hover:scale-[1.02]"
              }`}
            >

              {loading ? (
                <>
                  <div className="w-6 h-6 border-4 border-white border-t-transparent rounded-full animate-spin"></div>
                  Generating...
                </>
              ) : (
                <>
                  <FaMagic />
                  Generate AI Interview
                </>
              )}

            </button>

          </div>

          {/* Right */}

          <div className="bg-white rounded-3xl shadow-xl p-8">

            <h2 className="text-2xl font-bold mb-6 flex items-center gap-3">

              <FaClipboardList className="text-indigo-600" />

              Interview Tips

            </h2>

            <div className="space-y-5">

              <div className="flex gap-3">
                <FaCheckCircle className="text-green-500 mt-1" />
                <p>Read every question carefully.</p>
              </div>

              <div className="flex gap-3">
                <FaCheckCircle className="text-green-500 mt-1" />
                <p>Use project examples while answering.</p>
              </div>

              <div className="flex gap-3">
                <FaCheckCircle className="text-green-500 mt-1" />
                <p>Answer confidently and clearly.</p>
              </div>

              <div className="flex gap-3">
                <FaClock className="text-yellow-500 mt-1" />
                <p>Spend 1-2 minutes on each question.</p>
              </div>

            </div>

          </div>

        </div>

        {/* Questions */}

        {questions.length > 0 && (

          <div className="mt-10 bg-white rounded-3xl shadow-2xl overflow-hidden">

            <div className="bg-gradient-to-r from-green-600 via-blue-600 to-indigo-700 p-8 text-white">

              <h2 className="text-4xl font-bold">
                AI Interview Questions
              </h2>

              <p className="mt-2 text-blue-100">
                Practice one question at a time.
              </p>

            </div>

            <div className="p-8">

              <div className="flex justify-between mb-8">

                <h3 className="text-2xl font-bold">

                  Question {currentQuestion + 1} / {questions.length}

                </h3>

                <span className="font-semibold text-blue-600">

                  {Math.round(
                    ((currentQuestion + 1) / questions.length) * 100
                  )}%

                </span>

              </div>

              <div className="w-full h-3 rounded-full bg-gray-200 mb-8">

                <div
                  className="h-3 rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 transition-all"
                  style={{
                    width: `${((currentQuestion + 1) / questions.length) * 100}%`,
                  }}
                ></div>

              </div>

              <div className="bg-blue-50 border-l-8 border-blue-600 rounded-2xl p-8">

                <p className="text-2xl leading-10">

                  {questions[currentQuestion]}

                </p>

              </div>
                            <div className="flex justify-between mt-10">

                <button
                  disabled={currentQuestion === 0}
                  onClick={() =>
                    setCurrentQuestion(currentQuestion - 1)
                  }
                  className={`px-8 py-3 rounded-xl font-bold transition ${
                    currentQuestion === 0
                      ? "bg-gray-300 cursor-not-allowed"
                      : "bg-gray-800 text-white hover:bg-black"
                  }`}
                >
                  ⬅ Previous
                </button>

                <button
                  onClick={() => {
                    if (currentQuestion < questions.length - 1) {
                      setCurrentQuestion(currentQuestion + 1);
                    } else {
                      setCompleted(true);
                    }
                  }}
                  className="px-8 py-3 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-700 text-white font-bold hover:scale-105 transition flex items-center gap-2"
                >
                  {currentQuestion === questions.length - 1 ? (
                    <>
                      <FaCheckCircle />
                      Finish Interview
                    </>
                  ) : (
                    <>
                      Next
                      <FaArrowRight />
                    </>
                  )}
                </button>

              </div>

              {completed && (

                <div className="mt-12 bg-gradient-to-r from-green-500 via-emerald-600 to-teal-600 rounded-3xl p-10 text-white shadow-2xl">

                  <div className="text-center">

                    <div className="text-7xl mb-5">
                      🏆
                    </div>

                    <h2 className="text-4xl font-extrabold">
                      Interview Completed!
                    </h2>

                    <p className="mt-4 text-lg text-green-100">
                      Congratulations! You completed your AI Mock Interview.
                    </p>

                  </div>

                  <div className="grid md:grid-cols-3 gap-6 mt-10">

                    <div className="bg-white/20 backdrop-blur-lg rounded-2xl p-6 text-center">

                      <h3 className="font-semibold">
                        Questions
                      </h3>

                      <p className="text-4xl font-bold mt-3">
                        {questions.length}
                      </p>

                    </div>

                    <div className="bg-white/20 backdrop-blur-lg rounded-2xl p-6 text-center">

                      <h3 className="font-semibold">
                        Completion
                      </h3>

                      <p className="text-4xl font-bold mt-3">
                        100%
                      </p>

                    </div>

                    <div className="bg-white/20 backdrop-blur-lg rounded-2xl p-6 text-center">

                      <h3 className="font-semibold">
                        Rating
                      </h3>

                      <p className="text-4xl font-bold mt-3">
                        ⭐⭐⭐⭐⭐
                      </p>

                    </div>

                  </div>

                  <div className="mt-10 bg-white rounded-2xl p-8 text-gray-800">

                    <h3 className="text-2xl font-bold mb-5">
                      💡 AI Interview Tips
                    </h3>

                    <ul className="space-y-4 list-disc ml-6">

                      <li>Practice your answers aloud.</li>

                      <li>Use the STAR method for behavioral questions.</li>

                      <li>Support technical answers with project examples.</li>

                      <li>Research the company before the interview.</li>

                      <li>Repeat mock interviews for different job roles.</li>

                    </ul>

                  </div>

                </div>

              )}

            </div>

          </div>

        )}

      </div>

    </div>

  );
};

export default Interview;